SortSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from algorithm import views as algorithm_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^algorithm/', include('algorithm.urls')),
    url(r'^$', algorithm_views.index)
]

algorithm/urls.py
from django.conf.urls import url
from . import views

app_name = 'algorithm'

urlpatterns = [
    # /algorithm/ (default)
    url(r'^$', views.index, name='index'),

    #/algorithm/bigo
    url(r'^bigo/$', views.bigo, name='bigo'),

    # /algorithm/<sort_id>/
    url(r'^(?P<algorithm_id>[0-9]+)/$', views.sort_detail, name='sort_detail'),

    url(r'^(?P<algorithm_id>[0-9]+)/start/$', views.bubble_sort, name='start_sort'),
]

algorithm/models.py
from django.db import models

class Algorithm(models.Model):
    alg_name = models.CharField(max_length=50)
    alg_description = models.CharField(max_length=1500)
    alg_logo = models.CharField(max_length=1000)
    alg_complexity_average = models.CharField(max_length=20, default='DEFAULT VALUE')
    alg_complexity_best = models.CharField(max_length=20, default='DEFAULT VALUE')
    alg_complexity_worst = models.CharField(max_length=20, default='DEFAULT VALUE')

    def __str__(self):
        return self.alg_name

algorithm/views.py
from django.shortcuts import render, get_object_or_404
from .models import Algorithm

def index(request):
    all_algorithms = Algorithm.objects.all()
    context = {
        'all_algorithms' : all_algorithms,
    }
    return render(request, 'algorithm/index.html', context)

def bigo(request):
    all_algorithms = Algorithm.objects.all()
    context = {
        'all_algorithms' : all_algorithms,
    }
    return render(request, 'algorithm/bigo.html', context)

def sort_detail(request, algorithm_id):
    all_algorithms = Algorithm.objects.all()
    algorithm = get_object_or_404(Algorithm, pk=algorithm_id)
    sort_prefix = "algorithm/" + str(algorithm)[:-5].lower()
    sort_code = sort_prefix + "_code.html"
    sort_status = sort_prefix + "_status.html"
    context = {
        'all_algorithms' : all_algorithms,
        'algorithm' : algorithm,
        'sort_code' : sort_code,
        'sort_status' : sort_status
    }

    #if algorithm_id == "1":
        #return bubble_sort(request, algorithm_id, algorithm, numbers)

    return render(request, 'algorithm/sort_detail.html', context)

def bubble_sort(request, algorithm_id):

    algorithm = get_object_or_404(Algorithm, pk=algorithm_id)
    numbers = [5,9,3,4,1]

    for i in range(len(numbers)):
        for j in range(len(numbers)-1-i):
            if numbers[j] > numbers[j+1]:
                numbers[j], numbers[j+1] = numbers[j+1], numbers[j]

    for n in numbers:
        print(n)

    context = {
        'algorithm' : algorithm,
        'numbers' : numbers
    }

    return render(request, 'algorithm/sort_detail.html', context)

algorithm/templates/algorithm/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default{% endblock %}</title>
    <!-- Load static file -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'algorithm/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Salsa" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nova+Script" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- header  -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-items">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'algorithm:index' %}">SortSite</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="navbar-items">
                <ul class="nav navbar-nav">
                    <li class="divider-vertical"></li>
                    <li class="nav-item"><a href="{% url 'algorithm:bigo' %}">Big O Notation</a></li>
                    {% for algorithm in all_algorithms %}
                    <li class="nav-item"><a href="{% url 'algorithm:sort_detail' algorithm.id %}">{{ algorithm.alg_name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </nav>

    <div class="container main">
        {% block body %}
        {% endblock %}
    </div>

</body>

    <script src="{% static 'algorithm/sort.js' %}"></script>
    <script src="{% static 'algorithm/bigo.js' %}"></script>

</html>

algorithm/templates/algorithm/bigo.html
{% extends 'algorithm/base.html' %}
{% load static %}

{% block title %}Big O Notation{% endblock %}

{% block body %}

    <div class="row">

        <div class="jumbotron">
              <h2>Big O Notation</h2>
              <hr class="my-4">
        </div>

        <div class="col col-lg-1 col-md-1"></div>
        <div class="bigo-main container-fluid col col-lg-10 col-md-10 col-sm-12">

            <p><b>Big O Notation</b> in computer science is a way to represent the length of time an algorithm takes to execute.
                It is used to compare and understand the efficiency of different algorithms and approaches to mathematical problems.
                Naturally, this concept can be applied to sorting algorithms to compare the effectiveness of each algorithm.
            </p>

            <p>Here are some common Big O Notation time complexities that can be found in a variety of sorting algorithms:</p>
            <!-- CONSTANT -->
            <div class="spacer"></div>
            <h4>O(1) Constant Time</h4>
            <p>An algorithm with a constant time execution will always take the same amount of time to execute.
                The time to execute is independent of the input.
                The example below will always output the value in the array with the 3rd index regardless of the size of the array.
            </p>
            <pre>array = [1, 2, 3, 4, 5<span id="addConstantHere"></span>]
<c>print</c> array[3]

Output: <span id="outConstant"></span>
Run Time: <span id="runConstant"></span></pre>
            <form class="form-inline">
                <button type="button" class="btn" id="executeConstant">Execute</button>
                <button type="button" class="btn" id="addConstant">Append value</button>
            </form>
            <div class="spacer"></div>


            <!-- LINEAR -->
            <div class="spacer"></div>
            <h4>O(n) Linear Time</h4>
            <p>An algorithm with a linear time compelxity have execution time directly proportional to the size of it's input n.
                The example below demonstrates how the execution time increases as the input size n is increased.
            </p>
            <pre>array = [1, 2, 3, 4, 5<span id="addLinearHere"></span>]
<c>for</c> x <c>in</c> array:
    <c>print</c> array[x]

Output: <span id="outLinear"></span>
Run Time: <span id="runLinear"></span></pre>
            <form class="form-inline">
                <button type="button" class="btn" id="executeLinear">Execute</button>
                <button type="button" class="btn" id="addLinear">Append value</button>
            </form>
            <div class="spacer"></div>


            <!-- QUADRATIC -->
            <div class="spacer"></div>
            <h4>O(n<sup>2</sup>) Quadratic Time</h4>
            <p>An algorithm with quadratic time complexity will have execution time directly proportional to the square of input size n.
                The example below demonstrates how for loops can be nested within each other to create algorithms with quadratic time complexity.
                Increasing the amount of nested for loops will increase the time complexity exponential by 1 per loop, leading to cubic time complexity, then quartic time complexity and so forth.
                Many sorting algorithms feature the use of nested iterations like bubble sort, insertion sort and selection sort and as such have quadratic time complexity.
            </p>
            <pre>array = [1, 2, 3, 4, 5]
<c>for</c> x <c>in</c> array:
    <c>for</c> y <c>in</c> array:<span id="addQuadHere"></span>
        <span id="addQuadTabsHere"></span><c>print</c> array[x]

Output: <span id="outQuad"></span>
Run Time: <span id="runQuad"></span></pre>
            <form class="form-inline">
                <button type="button" class="btn" id="executeQuad">Execute</button>
                <button type="button" class="btn" id="addQuad">Append loop</button>
            </form>
            <div class="spacer"></div>


            <!-- LOGARITHMIC -->
            <div class="spacer"></div>
            <h4>O(log n) Logarithmic Time</h4>
            <p>An algorithm with logarithmic time complexity will have execution time proportional to the logarithm of the input size n.
                Sorting algorithms that use divide and conquer techniques like merge sort and quick sort have logarithmic time complexities.
            </p>
            <pre>array = [1, 2, 3, 4, 5, 6, 7, 8<span id="addLogHere"></span>]
<c>for</c> x = 1; x &lt; array.size; x = x * 2:
    <c>print</c> x

Output: <span id="outLog"></span>
Run Time: <span id="runLog"></span></pre>
            <form class="form-inline">
                <button type="button" class="btn" id="executeLog">Execute</button>
                <button type="button" class="btn" id="addLog">Append value</button>
            </form>

            <div class="spacer-big"></div>

        </div>
        <div class="col col-lg-1 col-md-1"></div>

    </div>


{% endblock %}

algorithm/templates/algorithm/bubble_code.html
<div class="code" id="code1"><p>swapped = true</p></div>
<div class="code" id="code2"><p>while swapped:</p></div>
<div class="code" id="code3" style="padding-left: 2em"><p>swapped = false</p></div>
<div class="code" id="code4" style="padding-left: 2em"><p>for elements from 0 to lastUnsortedElement:</p></div>
<div class="code" id="code5" style="padding-left: 4em"><p>if leftElement > rightElement:</p></div>
<div class="code" id="code6" style="padding-left: 6em"><p>swap leftElement and rightElement</p></div>
<div class="code" id="code7" style="padding-left: 6em"><p>swapped = true</p></div>

algorithm/templates/algorithm/bubble_status.html
<p class="status hide" id="slowMode">Slow down sorting animation to see taken actions</p>
<p class="status hide" id="status1">Set swapped flag to true and run loop</p>
<p class="status hide" id="status2">Set swapped flag to false and iterate from elements 1 to <span class="arrayLength">last unsorted</span></p>
<p class="status hide" id="status3">Compare elements <span class="bar1">[bar1]</span> and <span class="bar2">[bar2]</span></p>
<p class="status hide" id="status4">Swap elements <span class="bar1">[bar1]</span> and <span class="bar2">[bar2]</span> and set swapped flag to true</p>

algorithm/templates/algorithm/index.html
{% extends 'algorithm/base.html' %}
{% load static %}

{% block title %}SortSite: Learn sorting{% endblock %}

{% block body %}

    {% if all_algorithms %}
        <div class="row">

            <div class="jumbotron" style="padding-bottom:0;">
              <h2>SortSite</h2>
              <hr class="my-4">
              <p>Understand sorting algorithms</p>
            </div>

            <div class="row">
                <div class="col col-lg-2 col-md-2"></div>
                <div class="col col-lg-8 col-md-8">
                    <p>Sorting is the process of rearranging data into a defined pattern,
                        and is one of the most common, important and fundamental concepts studied in Computer Science.
                        Applications in the real world can be found across large varieties of types of software,
                        including database manipulation, compression utilities and computer games.
                    </p>
                    <p>This site aims to help you understand the concept of sorting and demonstrate how a variety of sorting algorithms function when applied to a problem.
                        There are many different techniques and algorithms used to perform sorting operations, with each having their own strengths and weaknesses.
                        Use the menu below to select a sorting algorithm you wish to explore and learn more about.</p>
                </div>
                <div class="col col-lg-2 col-md-2"></div>
            </div>
            <div class="spacer"></div>
            <div class="spacer"></div>

            <a href="{% url 'algorithm:bigo' %}">
                <div class="col-lg-4 col-md-4 col-sm-4 tile bigo">
                    <div class="tile-content">
                        <img class="tile-logo" src="{% static 'algorithm/images/on.png' %}"/>
                        <p class="tile-text">Big O notation</p>
                    </div>
                </div>
            </a>

            {% for algorithm in all_algorithms %}
            <a href="{% url 'algorithm:sort_detail' algorithm.id %}">
                <div class="col-lg-4 col-md-4 col-sm-4 tile {{algorithm.alg_logo}}">
                    <div class="tile-content">
                        <div class="table">
                            <div class="table-cell">
                                <img class="tile-logo" src="{% static 'algorithm/images/' %}{{ algorithm.alg_logo }}"/>
                                <p class="tile-text">{{ algorithm.alg_name }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}

            <!--
            <div class="col-lg-4 col-md-4 col-sm-4 tile"></div>
            <div class="col-lg-4 col-md-4 col-sm-4 tile"></div>
            <div class="col-lg-4 col-md-4 col-sm-4 tile"></div>
            -->

        </div>

    {% else %}
        <h3> No algorithms in database</h3>
    {% endif %}

{% endblock %}

algorithm/templates/algorithm/insertion_code.html
<div class="code" id="code1"><p>mark first element as sorted</p></div>
<div class="code" id="code2"><p>for each unsorted element i:</p></div>
<div class="code" id="code3"><p>select i</p></div>
<div class="code" id="code4" style="padding-left: 2em"><p>for j = lastSortedIndex to index 0: </p></div>
<div class="code" id="code5" style="padding-left: 4em"><p>if leftElement j > rightElement i</p></div>
<div class="code" id="code6" style="padding-left: 6em"><p>swap elements moving i to the left</p></div>
<div class="code" id="code7" style="padding-left: 4em"><p>else</p></div>
<div class="code" id="code8" style="padding-left: 6em"><p>break loop</p></div>

algorithm/templates/algorithm/insertion_status.html
<p class="status hide" id="slowMode">Slow down sorting animation to see taken actions</p>
<p class="status hide" id="status1">Mark first element as sorted</p>
<p class="status hide" id="status2">Iterate over unsorted elements, select element at index <span class="bar1">[bar1]</span></p>
<p class="status hide" id="status3">Select last sorted index at index <span class="bar1">[bar1]</span> and iterate to index 0</p>
<p class="status hide" id="status4">Compare elements at index <span class="bar1">[bar1]</span> and index <span class="bar2">[bar2]</span></p>
<p class="status hide" id="status5">Swap elements <span class="bar1">[bar1]</span> and <span class="bar2">[bar2]</span></p>
<p class="status hide" id="status6">No swap needed, break the loop</p>

algorithm/templates/algorithm/merge_code.html
<div class="code" id="code1"><p>split array into partitions of size 1</p></div>
<div class="code" id="code2"><p>for all partitions, merge adjacent partitions:</p></div>
<div class="code" id="code3" style="padding-left: 2em"><p>while leftPartition or rightPartition have elements:</p></div>
<div class="code" id="code4" style="padding-left: 4em"><p>if leftPartElement <= rightPartElement:</p></div>
<div class="code" id="code5" style="padding-left: 6em"><p>push leftPartElement to tempArray</p></div>
<div class="code" id="code6" style="padding-left: 4em"><p>else: </p></div>
<div class="code" id="code7" style="padding-left: 6em"><p>push rightPartElement to tempArray</p></div>
<div class="code" id="code8" ><p>select partition of mainArray</p></div>
<div class="code" id="code9" ><p>if mainArray is unordered:</p></div>
<div class="code" id="code10" style="padding-left: 2em;"><p>replace section of mainArray with tempArray</p></div>

algorithm/templates/algorithm/merge_status.html
<p class="status hide" id="slowMode">Slow down sorting animation to see taken actions</p>
<p class="status hide" id="status1">Split array into partitions of size 1 by recursively diving by 2</p>
<p class="status hide" id="status2">Iterate across all partitions, merging adjacent ones</p>
<p class="status hide" id="status3">Compare left partition element at position <span class="bar2">[bar2]</span> and right partition element at position <span class="bar1">[bar1]</span></p>
<p class="status hide" id="status4">Push left partition element at position <span class="bar1">[bar1]</span> to a temporary array</p>
<p class="status hide" id="status5">Push right partition element at position <span class="bar1">[bar1]</span> to a temporary array</p>
<p class="status hide" id="status6">Right partition has been sorted, so push left partition element at position <span class="bar1">[bar1]</span> to a temporary array</p>
<p class="status hide" id="status7">Left partition has benn sorted, so push right partition element at position <span class="bar1">[bar1]</span> to a temporary array</p>
<p class="status hide" id="status8">Select partition and check if it is unordered</p>
<p class="status hide" id="status9">Replace the main array with the temporary one created from sorting the partitions</p>

algorithm/templates/algorithm/quic_code.html
<div class="code" id="code1"><p>for each unsorted partition:</p></div>
<div class="code" id="code2" style="padding-left: 2em"><p>select a median pivot from first, last and middle elements</p></div>
<div class="code" id="code3" style="padding-left: 2em"><p>move pivot to end of unsorted partition</p></div>
<div class="code" id="code4" style="padding-left: 2em"><p>for elements from leftMostInPartition to rightMostInPartition:</p></div>
<div class="code" id="code5" style="padding-left: 4em"><p>if element[i] < element[end]:</p></div>
<div class="code" id="code6" style="padding-left: 6em"><p>if rightPartition is not empty:</p></div>
<div class="code" id="code7" style="padding-left: 8em"><p>swap leftElement and rightElement</p></div>
<div class="code" id="code8" style="padding-left: 4em"><p>else</p></div>
<div class="code" id="code9" style="padding-left: 6em"><p>mark purple as right partition</p></div>
<div class="code" id="code10" style="padding-left: 2em"><p>move lastElement to pivot point between partitions</p></div>

algorithm/templates/algorithm/quic_status.html
<p class="status hide" id="slowMode">Slow down sorting animation to see taken actions</p>
<p class="status hide" id="status1">For each unsorted partition select a median pivot from first, last and middle element, result = element at index <span class="bar1">[bar1]</span></p>
<p class="status hide" id="status2">Move pivot at index <span class="bar1">[bar1]</span> to last index position</span></p>
<p class="status hide" id="status3">Compare element at index <span class="bar2">[bar1]</span> and pivot element at index <span class="bar1">[bar2]</span></p>
<p class="status hide" id="status4">Check if right partition is not empty</p>
<p class="status hide" id="status5">Swap element at index <span class="bar2">[bar1]</span> and element at index <span class="bar1">[bar2]</span></p>
<p class="status hide" id="status6">Mark element at index <span class="bar1">[bar1]</span> as right partition</p>
<p class="status hide" id="status7">Swap pivot element at index <span class="bar1">[bar1]</span> to inbetween partitions at index <span class="bar2">[bar2]</span></p>

algorithm/templates/algorithm/selection_code.html
<div class="code" id="code1"><p>for all elements:</p></div>
<div class="code" id="code2" style="padding-left: 2em"><p>set first element as minimum</p></div>
<div class="code" id="code3" style="padding-left: 2em"><p>for elements from firstUnsortedElement to lastElement:</p></div>
<div class="code" id="code4" style="padding-left: 4em"><p>if element < currentMinimum:</p></div>
<div class="code" id="code5" style="padding-left: 6em"><p>set new minimumElement</p></div>
<div class="code" id="code6" style="padding-left: 2em"><p>swap minimumElement and firstUnsortedElement</p></div>

algorithm/templates/algorithm/selection_status.html
<p class="status hide" id="slowMode">Slow down sorting animation to see taken actions</p>
<p class="status hide" id="status1">Iterate over elements</p>
<p class="status hide" id="status2">Set first unsorted element at position <span class="bar1">[bar1]</span> to minimum and iterate from first unsorted to last unsorted</span></p>
<p class="status hide" id="status3">Compare current minimum element <span class="bar1">[bar1]</span> and element <span class="bar2">[bar2]</span></p>
<p class="status hide" id="status4">Set new minimum element at position <span class="bar1">[bar1]</span></p>
<p class="status hide" id="status5">Swap minimum element <span class="bar2">[bar2]</span> to first unsorted position <span class="bar1">[bar1]</span></p>

algorithm/templates/algorithm/sort_detail.html
{% extends 'algorithm/base.html' %}
{% load static %}

{% block title %}{{ algorithm.alg_name }}{% endblock %}

{% block body %}

    <div class="spacer"></div>

    <table>
        <tr>
            <th><h1>{{ algorithm.alg_name }}</h1></th>
            <th><img width="60" height="60" style="margin-left:15px;" src="{% static 'algorithm/images/' %}{{ algorithm.alg_logo }}"></th>
        </tr>
    </table>

    <div class="row">
        <div class="col col-lg-1 col-md-1"></div>

        <div class="col col-lg-10 col-md-10">
            <div class="spacer"></div>
            <p>{{ algorithm.alg_description | safe }}</p>
            <!-- Description from https://www.geeksforgeeks.org/merge-sort/-->
            <p></p>
            <p><b>Instructions:</b> The controls below can be used to run an example of the <b>{{algorithm.alg_name}}</b> algorithm.
            Set the size of the array to be sorted and the time interval between actions and then press <i>Start Sort</i> to see the algorithm at work.
            Use the <i>Pause</i> button to pause the algorithm at any time and use the <i>Step</i> button to advance the algorithm at your own pace.
            Once you feel like you understand the algorithm press <i>Start</i> in the <i>Test your knowledge</i> section to quiz yourself.</p>
        </div>

        <div class="col col-lg-1 col-md-1"></div>
    </div>
    <!--{% for n in numbers %}
        <p>{{ n }}</p>
    {% endfor %}-->

    <!--<form action="{% url 'algorithm:start_sort' algorithm.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Start sort">
    </form>-->

    <div class="spacer"></div>
    <script>var alg_name = "{{algorithm.alg_name}}";</script>
    <div class="container-fluid">

        <div class="row">
            <form class="form-inline">
                <div class="form-group">
                    <label for="formArraySize">Size:</label>
                    <input id="formArraySize" class="form-control" type="number" value="15"/>
                </div>
                <div class="form-group">
                    <label for="formInterval">Time interval (ms):</label>
                    <input id="formInterval" class="form-control" type="number" value="500"/>
                </div>
                <button type="button" class="btn" id="start" >Start sort</button>
                <button type="button" class="btn" id="pause" >Pause</button>
                <button type="button" class="btn" id="step" >Step</button>
            </form>
        </div>

        <p></p>
        <div class="row">

            <div class="col col-lg-7 col-md-7 col-sm-7" id="canvas-container">

                <table class="table">
                    <tr>
                        <td><p>Comparisons are <span class="orange">orange</span></p></td>
                        <td><p>Swaps are <span class="red">red</span></p></td>
                        <td><p>Selected elements are <span class="purple">purple</span></p></td>
                    </tr>
                </table>

                <canvas id="sort-canvas" width="" height="500"></canvas>

                <div class="row status-container">
                    <div class="col col-lg-2 col-md-2 col-sm-2 status-title">
                        <h4 class="align-text-middle">Action</h4>
                    </div>

                    <div class="col col-lg-10 col-md-10 col-sm-10">
                        {% include sort_status %}
                    </div>
                </div>

                <div class="spacer"></div>
                <div class="spacer"></div>

                <table class="table">
                    <caption><b>{{ algorithm.alg_name }} Time Complexity</b></caption>
                    <tr>
                        <td><p>Average: {{ algorithm.alg_complexity_average }}</p></td>
                        <td><p>Best: {{ algorithm.alg_complexity_best }}</p></td>
                        <td><p>Worst: {{ algorithm.alg_complexity_worst }}</p></td>
                    </tr>
                </table>

                <div class="spacer-big"></div>
            </div>

            <div class="col col-lg-1 col-md-1 col-sm-1"></div>

            <div class="col col-lg-4 col-md-4 col-sm-4">

                <div class="code-container">
                    <h3>Pseudocode</h3>
                    {% include sort_code %}
                </div>

                <div class="spacer"></div>

                <div class="code-container">
                    <h3>Test your knowledge</h3>
                    <button type="button" class="quiz-btn" id="quiz">Start</button>
                    <div class="code hide" id="question"><p>Select the next action that the {{algorithm.alg_name}} algorithm will perform:</p></div>
                    <div class="answers">
                        <div class="code answer correct hide" id="answer1"></div>
                        <div class="code answer false hide" id="answer2"></div>
                        <div class="code answer false hide" id="answer3"></div>
                    </div>
                    <div class="result hide" id="result-correct">Correct!</div>
                    <div class="result hide" id="result-incorrect">Inorrect!</div>
                </div>

            </div>

        </div>
    </div>

{% endblock %}